#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if less than 4 parameters passed
if [ "$#" -lt 3 ]; then
    usage
elif [ "$#" -lt 4 ]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
