#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Creating a simple HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx without using systemctl
service nginx start