#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx without using systemctl
killall -s HUP nginx || true
