#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page that contains
# the string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World! This is ALX_Africa" | sudo tee /var/www/html/index.html

redirect_config="server_name _;\n\trewrite ^\/redirect_me https:\/\/eztosin.hashnode.dev\/ permanent;"
sudo sed -i "s/server_name _;/$redirect_config/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

error_config="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$error_config/" /etc/nginx/sites-enabled/default

sudo service nginx restart
