#!/usr/bin/env bash
# what’s keeping Ubuntu container’s Nginx installation from listening on port 80

if ! dpkg -s nginx > /dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get -y install nginx
    sudo ufw allow 'Nginx HTTP'
fi

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo service nginx restart
