#!/usr/bin/env bash
# A script that displays Best School 10 times using while loop

display="Best School"
text1="bad luck"
text2="good luck"
count=10
i=1

while [ $i -le $count ]
do
    if [ $i -eq 4 ]
    then
	echo "$text1"
    elif [ $i -eq 8 ]
    then
	echo "$text2"
    else
	echo "$display"
    fi
    ((i++))
done
