#!/usr/bin/env bash
# A script that displays numbers from 1 - 20 using while loop
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

count=20
i=1

while [ $i -le $count ]
do
    case $i in
	4)
	    echo "$i bad luck from China"
	    ;;
	9)
	    echo "$i bad luck from Japan"
	    ;;
	17)
	    echo "$i bad luck from Italy"
	    ;;
	*)
	    echo "$i"
    esac
    ((i++))
done
