#!/usr/bin/env bash
# displays the content of the current directory in a list format
# displays only the content after the first dash

list=$(ls)

for i in $list;
do
    echo "$i" | cut -d "-" -f2
done
