#!/usr/bin/env bash
# a Bash script that accepts one argument

if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Get the username from the first argument
username=$1

# Run whoami command under the specified user
sudo -u "$username" whoami
